💫 main level animations
Rogue-Ape-Studios-XR/Secrets-of-Ignacios pull request #137
Opened 2024-10-31 13:48 UTC by LJRReyniers

## Content

Added the dubble door, big gate, pedestal and chain animations.

## Changes
### Added
`Assets/Animations/BigGate.controller` : Was created. 
`Assets/Animations/BigGateOpen.anim` : Was created. 
`Assets/Animations/Cain.controller` : Was created. 
`Assets/Animations/ChainDown.anim` : Was created.
`Assets/Animations/DubbleDoor.controller` : Was created. 
`Assets/Animations/Dubble_in.anim` : Was created. 
`Assets/Animations/Dubble_out.anim` : Was created. 
`Assets/Animations/Pedestal.controller` : Was created. 
`Assets/Animations/Turn.anim` : Was created. 

## Testing

https://github.com/user-attachments/assets/660d18b2-67c2-4a94-89f9-c9b3bbb96472

2024-10-31 14:21 UTC, Timsel1 requested changes
No way for me to test, I assume you created prefabs, and made the animation in the prefab view, otherwise there is a risk this animation may only work in a scene at the exact world coordinated they were created at.

2024-10-31 14:21 UTC, Timsel1 commented on Assets/Animations/Dubble_out.anim.meta
Keep naming consistent

2024-10-31 14:21 UTC, Timsel1 commented on Assets/Animations/Dubble_out.anim
Keep naming consistent

2024-11-04 09:17 UTC, davey2206 approved these changes

2024-11-04 09:18 UTC, Timsel1 approved these changes

2024-11-04 09:19 UTC, merged