🐛teleport
Rogue-Ape-Studios-XR/Secrets-of-Ignacios pull request #192
Opened 2024-11-29 13:19 UTC by davey2206

## Content

Fixed teleport bugs (see closes issues)

## Changes

### Updated
`ProjectSettings/TagManager.asset` : Was updated to have a floor tag
`Assets/Scripts/Teleport/HandleHandTeleport.cs`: Was updated to disable teleport after x seconds
`Assets/Scenes/MainLevel.unity`: Updated Teleport areas
`Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Shapes/Point Hand Shape.asset`: Was updated to allow for easier teleporting
`Assets/Prefabs/PlayerRig/PlayerRig.prefab`: Was updated

## Testing

The feature / Bugfix can be testing by following these steps:

1. Open the scene
2. Play around with teleport

Closes #177, #181, #179, #180, #167, #168, #176

2024-12-02 12:02 UTC, Timsel1 requested changes
|Fix this|I have commented how to fix this|
|-|-|
|https://github.com/user-attachments/assets/898ad507-07de-4f94-b937-82de1f166776|https://github.com/user-attachments/assets/06b343bc-0afe-495c-bfee-446666e45444|

2024-12-02 12:02 UTC, Timsel1 commented on Assets/Scripts/Teleport/HandleHandTeleport.cs
> +                _cancellationTokenSourceTeleport.Cancel();
3 Lines of disposing and creating new token are in the wrong place, it should be here:
```c#
public void TriggerTeleport()
        {
            _alternateMovement.enabled = false;
            if (_isTeleportActive && _teleportInteractor.TryGetCurrent3DRaycastHit(out RaycastHit hit))
            {
                TeleportRequest request = new()
                {
                    destinationPosition = hit.point,
                };
                _teleportationProvider.QueueTeleportRequest(request);
            }
            _cancellationTokenSourceTeleport.Cancel();
            _cancellationTokenSourceTeleport.Dispose();
            _cancellationTokenSourceTeleport = new();

            EnableMovement(_cancellationTokenSource.Token);
        }
```

2024-12-03 10:21 UTC, davey2206 commented on Assets/Scripts/Teleport/HandleHandTeleport.cs
> +                _cancellationTokenSourceTeleport.Cancel();
done

2024-12-03 10:51 UTC, LucVogelsangs requested changes
Hole from start room to teleport room is walkable

2024-12-03 11:03 UTC, LucVogelsangs approved these changes

2024-12-03 11:32 UTC, Timsel1 approved these changes
hoop t

2024-12-03 11:32 UTC, merged